### ISSUE TITLE
Add support for ssh-agent to ssh transport

### ISSUE THREAD

**Issue by garrickpeterson-wf** [chef/train#129]
NET::SSH supports using an SSH agent for ssh authentication, however train blows up if a keypath or password auth is not provided. Instead, it should allow for either the specification of using ssh agent, or allow the underlying NET::SSH library to try and use agent authentication if its available.

I ran across this by trying to run inspec in a docker container by providing access to the SSH agent socket and setting the SSH_AUTH_SOCK environment variable to point at it, but if '-t ssh://' is provided and neither '-i' or '--password' are provided, train throws an exception saying that one or the other is required.

**Comment by dustyburwell** [comment]
I've also run into this issue after configuring my `~/.ssh/config` with `IdentityFile` directives. Similarly, I would expect this to Just Work™.

**Comment by ouroboros8** [comment]
I ran in to this today while using [kitchen-inspec](https://github.com/chef/kitchen-inspec). I use GPG Auth keys for SSH authentication, so I can't even work around this by pointing to a keyfile on disk (because there isn't one).

**Comment by jalberti** [comment]
See https://github.com/chef/train/pull/183 this should fix the issue, I was also just coming across the kitchen inspec issue

**Comment by chris-rock** [comment]
This issues was fixed by #165. @jalberti @ouroboros8 lets open another issue for the cases you run into
