### ISSUE TITLE
Train doesn't create a login shell

### ISSUE THREAD

**Issue by jonathanmorley** [chef/train#148]
``` ruby
require 'train'

train = Train.create('ssh', host: '127.0.0.1', port: 2200, user: 'vagrant', password: 'vagrant')
conn = train.connection
puts conn.run_command("shopt -q login_shell && echo 'Login shell' || echo 'Not login shell'").stdout
```

Expected output `Login shell`
Actual output `Not login shell`

Since train 'logs in' to the remote host, and then runs commands against them, I would expect the resulting shells to be login shells.

I think a `login` parameter should be added to somehow force train to create a login shell (defaulted to false for backwards compatibility).

**Comment by jonathanmorley** [comment]
The main driver for this issue is that inspec tests can return different results than manual ssh, since login shells will source the /etc/profile file.

**Comment by chris-rock** [comment]
@jonathanmorley I really like that option. I see the point that paths etc may not be loaded. I just want to make sure we keep the default as is and make this fully optional. If users need this behavior, he should have the power to do so 👍
