### ISSUE TITLE
Cannot install train on Windows with ChefDK if username >9 chars in length due to spec filename lengths in docker-api gem.

### ISSUE THREAD

**Issue by stuartpreston** [chef/train#28]
The ```docker-api 1.22.4``` gem which train depends on via the .gemspec appears to bundle specs that go beyond the file length limit of Windows (260 chars) when installed on my system.

Error seen:
```
C:\Users\StuartPreston> chef gem install r-train
WARNING:  You don't have c:\users\stuartpreston\appdata\local\chefdk\gem\ruby\2.1.0\bin in your PATH,
          gem executables will not run.
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - C:/Users/StuartPreston/AppData/Local/chefdk/gem/ruby/2.1.0/gems/docker-api-1.22.4/spec/vcr/Docker_Image/_build_from_dir/with_a_valid_Dockerfile/with_a_block_capturing_build_output/uses_a_cached_version_the_second_time/calls_the_block_and_passes_build_output.yml
C:\Users\StuartPreston>
```

By my calculations I believe that means only users with usernames less than 10 characters in length can install r-train on Windows at the moment but I'm doing some more testing. Thought I'd get an early report in as I'm sure others will see it.

Looks like a similar issue was encountered before by @someara in chef-docker: https://github.com/someara/chef-docker/issues/357 with the outcome being to vendor in the gems but remove the specs...

I would report this in docker-api but it's a combination of their spec length and the location of the ChefDK gems on Windows and the length of the username in combination that appear to be the problem.

Thoughts?

**Edit**: My own workaround for now is to build the docker-api gem from source, but without the specs then installed into the ChefDK. Note you have to clone into a folder near the root of a drive to avoid the path length failures.

**Comment by chris-rock** [comment]
@stuartpreston Thanks for reporting this. We work on improving the Windows support and ease the use for Windows within the next weeks. This includes an easy installation.

**Comment by chris-rock** [comment]
Train is able to run locally on Windows now with #43

**Comment by chris-rock** [comment]
@stuartpreston is this still valid with the latest version?

**Comment by stuartpreston** [comment]
I just tried on a clean Windows 10 machine with ChefDK 0.10.0 and the install works fine now. Great job.

```
PS C:\Users\stuartpreston> chef gem install r-train
Fetching: r-train-0.9.4.gem (100%)
WARNING:  You don't have c:\users\stuartpreston\appdata\local\chefdk\gem\ruby\2.1.0\bin in your PATH,
          gem executables will not run.
Successfully installed r-train-0.9.4
Parsing documentation for r-train-0.9.4
Installing ri documentation for r-train-0.9.4
Done installing documentation for r-train after 2 seconds
1 gem installed
PS C:\Users\stuartpreston>
```
